FROM debian:trixie-slim
ENV DEBIAN_FRONTEND=noninteractive
ENV GOROOT=/usr/local/go
ENV GOPATH=/go
ENV GOVERSION=1.24.1
ENV PATH=$GOROOT/bin:$GOPATH/bin:$PATH

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    make \
    bash \
    zip \
    unzip \
    docker.io \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://go.dev/dl/go$GOVERSION.linux-amd64.tar.gz | \
    tar -v -C /usr/local -xzf - \
    && mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

WORKDIR /workspace

ARG GIT_URL="https://github.com/SKBCloudX/eSDK_K8S_Plugin.git"

#RUN git clone --no-single-branch --tags ${GIT_URL} .

#ENTRYPOINT ["bash", "build.sh"]
#CMD ["4.11.0", "X86"]
