FROM debian:trixie-slim
ENV DEBIAN_FRONTEND=noninteractive
ENV GOROOT=/usr/local/go
ENV GOPATH=/go
ENV GOVERSION=1.24.1
ENV PATH=$GOROOT/bin:$GOPATH/bin:$PATH
ENV WORKSPACE=/workspace
ENV DOCKER_URL="https://download.docker.com/linux/debian"
ENV GIT_URL="https://github.com/SKBCloudX/eSDK_K8S_Plugin"

WORKDIR ${WORKSPACE}
COPY scripts ${WORKSPACE}/scripts

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    make \
    bash \
    zip \
    unzip \
    ca-certificates \
    gnupg \
    libarchive-tools \
    && install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL ${DOCKER_URL}/gpg -o /etc/apt/keyrings/docker.asc \
    && chmod a+r /etc/apt/keyrings/docker.asc \
    && cp ${WORKSPACE}/scripts/docker.sources /etc/apt/sources.list.d/

RUN apt-get update && apt-get install -y --no-install-recommends \
    docker-ce-cli \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://go.dev/dl/go$GOVERSION.linux-amd64.tar.gz | \
    tar -v -C /usr/local -xzf - \
    && mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

ENTRYPOINT ["/workspace/scripts/image_builder.sh"]
